// @king-card/shared - 游戏常量

export const GAME_CONSTANTS = {
  INITIAL_HEALTH: 30,
  DECK_SIZE: 30,
  STARTING_HAND_SIZE: 4,
  MAX_HAND_SIZE: 10,
  MAX_BOARD_SIZE: 7,
  MAX_ENERGY: 10,
  EMPEROR_SOFT_LIMIT: 4,
  GENERAL_DECK_LIMIT: 2,
  SORCERY_DECK_LIMIT: 2,
  FIRST_TURN_ENERGY: 1,
  ENERGY_PER_TURN: 1,
} as const;
