import type { Card, GeneralSkill, HeroSkill, Keyword, Minister, MinisterSkill } from '@king-card/shared';
import { DEFAULT_LOCALE, type SupportedLocale } from './locale.js';

interface CardTextCarrier {
  name: string;
  description: string;
  heroSkill?: HeroSkill;
  generalSkills?: GeneralSkill[];
}

export const KEYWORD_LABELS: Record<SupportedLocale, Record<string, string>> = {
  'zh-CN': {
    BATTLECRY: '战吼',
    DEATHRATTLE: '亡语',
    AURA: '光环',
    TAUNT: '嘲讽',
    RUSH: '突袭',
    CHARGE: '冲锋',
    ASSASSIN: '刺杀',
    COMBO_STRIKE: '连击',
    STEALTH_KILL: '暗杀',
    MOBILIZE: '动员',
    GARRISON: '驻守',
    IRON_FIST: '铁拳',
    RESEARCH: '研究',
    BLOCKADE: '封锁',
    COLONY: '殖民',
    BLITZ: '闪击',
    MOBILIZATION_ORDER: '动员令',
    DIVINE_SHIELD: '圣盾',
    POISONOUS: '剧毒',
    WINDFURY: '风怒',
    LIFESTEAL: '吸血',
    REBORN: '重生',
  },
  'en-US': {
    BATTLECRY: 'Battlecry',
    DEATHRATTLE: 'Deathrattle',
    AURA: 'Aura',
    TAUNT: 'Taunt',
    RUSH: 'Rush',
    CHARGE: 'Charge',
    ASSASSIN: 'Assassin',
    COMBO_STRIKE: 'Combo Strike',
    STEALTH_KILL: 'Stealth Kill',
    MOBILIZE: 'Mobilize',
    GARRISON: 'Garrison',
    IRON_FIST: 'Iron Fist',
    RESEARCH: 'Research',
    BLOCKADE: 'Blockade',
    COLONY: 'Colony',
    BLITZ: 'Blitz',
    MOBILIZATION_ORDER: 'Mobilization Order',
    DIVINE_SHIELD: 'Divine Shield',
    POISONOUS: 'Poisonous',
    WINDFURY: 'Windfury',
    LIFESTEAL: 'Lifesteal',
    REBORN: 'Reborn',
  },
};

const TEXT_RESOURCE_TABLE: Record<string, Partial<Record<SupportedLocale, string>>> = {
  '亚伯拉罕·林肯': { 'en-US': 'Abraham Lincoln' },
  '解放宣言': { 'en-US': 'Emancipation Proclamation' },
  '帝王技能：所有友方生物恢复2点生命。入场时所有友方生物获得+1生命。': {
    'en-US': 'Hero Skill: Restore 2 Health to all friendly minions. On play, all friendly minions gain +1 Health.',
  },
  '所有友方生物恢复2点生命': { 'en-US': 'Restore 2 Health to all friendly minions' },
  '乔治·华盛顿': { 'en-US': 'George Washington' },
  '大陆军号令': { 'en-US': 'Continental Army Command' },
  '帝王技能：所有友方生物获得+1攻击。入场时获得3点护甲。': {
    'en-US': 'Hero Skill: Give all friendly minions +1 Attack. On play, gain 3 Armor.',
  },
  '所有友方生物获得+1攻击': { 'en-US': 'Give all friendly minions +1 Attack' },
  '富兰克林·罗斯福': { 'en-US': 'Franklin D. Roosevelt' },
  '帝王技能：召唤一个3/3大兵。入场时所有友方生物获得+1生命。': {
    'en-US': 'Hero Skill: Summon a 3/3 GI. On play, all friendly minions gain +1 Health.',
  },
  '召唤一个3/3大兵': { 'en-US': 'Summon a 3/3 GI' },
  '纳撒尼尔·格林': { 'en-US': 'Nathanael Greene' },
  '嘲讽。技能①南方机动：对一个敌方生物造成4点伤害。技能②拖延战术：获得+0/+3。技能③坚守福吉谷：所有友方生物获得+1生命。': {
    'en-US': 'Taunt. Skill 1: Southern Maneuver — deal 4 damage to an enemy minion. Skill 2: Delaying Tactics — gain +0/+3. Skill 3: Hold Valley Forge — all friendly minions gain +1 Health.',
  },
  '南方机动': { 'en-US': 'Southern Maneuver' },
  '拖延战术': { 'en-US': 'Delaying Tactics' },
  '坚守福吉谷': { 'en-US': 'Hold Valley Forge' },
  '对一个敌方生物造成4点伤害': { 'en-US': 'Deal 4 damage to an enemy minion' },
  '获得+0/+3': { 'en-US': 'Gain +0/+3' },
  '所有友方生物获得+1生命': { 'en-US': 'All friendly minions gain +1 Health' },
  '亨利·诺克斯': { 'en-US': 'Henry Knox' },
  '冲锋。技能①炮兵统率：对所有敌方生物造成2点伤害。技能②大陆军整编：所有友方生物获得+1攻击。技能③火炮援护：召唤一个3/3大兵。': {
    'en-US': 'Charge. Skill 1: Artillery Command — deal 2 damage to all enemy minions. Skill 2: Continental Reorganization — give all friendly minions +1 Attack. Skill 3: Artillery Support — summon a 3/3 GI.',
  },
  '炮兵统率': { 'en-US': 'Artillery Command' },
  '大陆军整编': { 'en-US': 'Continental Reorganization' },
  '火炮援护': { 'en-US': 'Artillery Support' },
  '对所有敌方生物造成2点伤害': { 'en-US': 'Deal 2 damage to all enemy minions' },
  '道格拉斯·麦克阿瑟': { 'en-US': 'Douglas MacArthur' },
  '突袭。技能①跳岛战术：对一个敌方生物造成4点伤害。技能②我将归来：召唤一个3/3空降兵。技能③远东统帅：所有友方生物获得突袭（本回合）。': {
    'en-US': 'Rush. Skill 1: Island Hopping — deal 4 damage to an enemy minion. Skill 2: I Shall Return — summon a 3/3 Airborne. Skill 3: Far East Commander — all friendly minions gain Rush this turn.',
  },
  '跳岛战术': { 'en-US': 'Island Hopping' },
  '我将归来': { 'en-US': 'I Shall Return' },
  '远东统帅': { 'en-US': 'Far East Commander' },
  '召唤一个3/3空降兵': { 'en-US': 'Summon a 3/3 Airborne' },
  '所有友方生物获得突袭（本回合）': { 'en-US': 'All friendly minions gain Rush this turn' },
  '德怀特·艾森豪威尔': { 'en-US': 'Dwight D. Eisenhower' },
  '嘲讽。技能①霸王行动：对所有敌方生物造成3点伤害。技能②盟军总司令：所有友方生物获得+1/+1。技能③后勤大师：抽一张牌。': {
    'en-US': 'Taunt. Skill 1: Operation Overlord — deal 3 damage to all enemy minions. Skill 2: Supreme Allied Commander — all friendly minions get +1/+1. Skill 3: Logistics Master — draw 1 card.',
  },
  '霸王行动': { 'en-US': 'Operation Overlord' },
  '盟军总司令': { 'en-US': 'Supreme Allied Commander' },
  '后勤大师': { 'en-US': 'Logistics Master' },
  '对所有敌方生物造成3点伤害': { 'en-US': 'Deal 3 damage to all enemy minions' },
  '所有友方生物获得+1/+1': { 'en-US': 'All friendly minions get +1/+1' },
  '抽一张牌': { 'en-US': 'Draw 1 card' },
  '约翰·亚当斯': { 'en-US': 'John Adams' },
  '独立辩论': { 'en-US': 'Independence Debate' },
  '托马斯·潘恩': { 'en-US': 'Thomas Paine' },
  '常识': { 'en-US': 'Common Sense' },
  '对手随机弃一张牌': { 'en-US': 'Opponent discards 1 random card' },
  '亨利·劳伦斯': { 'en-US': 'Henry Laurens' },
  '大陆后勤': { 'en-US': 'Continental Logistics' },
  '获得2点护甲': { 'en-US': 'Gain 2 armor' },
  '埃莉诺·罗斯福': { 'en-US': 'Eleanor Roosevelt' },
  '民生救济': { 'en-US': 'Relief Effort' },
  '恢复英雄3点生命': { 'en-US': 'Restore 3 Health to your hero' },
  '哈里·霍普金斯': { 'en-US': 'Harry Hopkins' },
  '乔治·马歇尔': { 'en-US': 'George Marshall' },
  '参谋联席': { 'en-US': 'Joint Chiefs' },
  '大陆会议': { 'en-US': 'Continental Congress' },
  '抽两张牌。': { 'en-US': 'Draw 2 cards.' },
  '福吉谷冬训': { 'en-US': 'Valley Forge' },
  '所有友方生物获得+1/+1。': { 'en-US': 'All friendly minions get +1/+1.' },
  '新政': { 'en-US': 'New Deal' },
  '抽一张牌并获得4点护甲。': { 'en-US': 'Draw 1 card and gain 4 armor.' },
  '诺曼底登陆': { 'en-US': 'D-Day Landing' },
  '召唤一个3/3空降兵，并对所有敌方生物造成1点伤害。': {
    'en-US': 'Summon a 3/3 Airborne and deal 1 damage to all enemy minions.',
  },
  '维多利亚女王': { 'en-US': 'Queen Victoria' },
  '帝国号令': { 'en-US': 'Imperial Command' },
  '帝王技能：所有友方生物获得+1/+1。入场时获得3点护甲。': {
    'en-US': 'Hero Skill: All friendly minions get +1/+1. On play, gain 3 Armor.',
  },
  '伊丽莎白一世': { 'en-US': 'Elizabeth I' },
  '黄金时代': { 'en-US': 'Golden Age' },
  '帝王技能：抽一张牌。入场时获得2点护甲。': {
    'en-US': 'Hero Skill: Draw 1 card. On play, gain 2 Armor.',
  },
  '抽一张牌。': { 'en-US': 'Draw 1 card.' },
  '温斯顿·丘吉尔': { 'en-US': 'Winston Churchill' },
  '最光辉时刻': { 'en-US': 'Their Finest Hour' },
  '帝王技能：所有友方生物获得+1攻击。入场时获得5点护甲。': {
    'en-US': 'Hero Skill: Give all friendly minions +1 Attack. On play, gain 5 Armor.',
  },
  '罗伯特·达德利': { 'en-US': 'Robert Dudley' },
  '冲锋。技能①宫廷集结：召唤一个2/2皇家卫队。技能②宠臣策动：一个友方生物获得+2攻击。技能③海权筹备：抽一张牌。': {
    'en-US': 'Charge. Skill 1: Court Muster — summon a 2/2 Royal Guard. Skill 2: Favorite of the Queen — give a friendly minion +2 Attack. Skill 3: Naval Preparations — draw 1 card.',
  },
  '宫廷集结': { 'en-US': 'Court Muster' },
  '宠臣策动': { 'en-US': 'Favorite of the Queen' },
  '海权筹备': { 'en-US': 'Naval Preparations' },
  '召唤一个2/2皇家卫队': { 'en-US': 'Summon a 2/2 Royal Guard' },
  '一个友方生物获得+2攻击': { 'en-US': 'Give a friendly minion +2 Attack' },
  '威廉·塞西尔': { 'en-US': 'William Cecil' },
  '嘲讽。技能①王国理财：获得3点护甲。技能②情报网络：对手随机弃一张牌。技能③女王亲军：所有友方生物获得+1生命。': {
    'en-US': 'Taunt. Skill 1: Royal Treasury — gain 3 Armor. Skill 2: Intelligence Network — opponent discards 1 random card. Skill 3: Queen\'s Household Guard — all friendly minions gain +1 Health.',
  },
  '王国理财': { 'en-US': 'Royal Treasury' },
  '情报网络': { 'en-US': 'Intelligence Network' },
  '女王亲军': { 'en-US': 'Queen\'s Household Guard' },
  '获得3点护甲': { 'en-US': 'Gain 3 armor' },
  '伯纳德·蒙哥马利': { 'en-US': 'Bernard Montgomery' },
  '突袭。技能①阿拉曼战役：对所有敌方生物造成2点伤害。技能②沙漠反攻：所有友方生物获得+1攻击。技能③步坦协同：召唤一个3/3皇家卫队。': {
    'en-US': 'Rush. Skill 1: Battle of El Alamein — deal 2 damage to all enemy minions. Skill 2: Desert Counteroffensive — give all friendly minions +1 Attack. Skill 3: Combined Arms — summon a 3/3 Royal Guard.',
  },
  '阿拉曼战役': { 'en-US': 'Battle of El Alamein' },
  '沙漠反攻': { 'en-US': 'Desert Counteroffensive' },
  '步坦协同': { 'en-US': 'Combined Arms' },
  '召唤一个3/3皇家卫队': { 'en-US': 'Summon a 3/3 Royal Guard' },
  '艾伦·布鲁克': { 'en-US': 'Alan Brooke' },
  '嘲讽。技能①帝国参谋本部：抽一张牌。技能②本土防御：所有友方生物获得+1/+1。技能③联合作战：对一个敌方生物造成5点伤害。': {
    'en-US': 'Taunt. Skill 1: Imperial General Staff — draw 1 card. Skill 2: Home Defense — all friendly minions get +1/+1. Skill 3: Joint Operations — deal 5 damage to an enemy minion.',
  },
  '帝国参谋本部': { 'en-US': 'Imperial General Staff' },
  '本土防御': { 'en-US': 'Home Defense' },
  '联合作战': { 'en-US': 'Joint Operations' },
  '对一个敌方生物造成5点伤害': { 'en-US': 'Deal 5 damage to an enemy minion' },
  '弗朗西斯·沃尔辛厄姆': { 'en-US': 'Francis Walsingham' },
  '王室密探': { 'en-US': 'Royal Spymaster' },
  '伯利勋爵': { 'en-US': 'Lord Burghley' },
  '国库整顿': { 'en-US': 'Treasury Reform' },
  '埃塞克斯伯爵': { 'en-US': 'Earl of Essex' },
  '女王宠臣': { 'en-US': 'Queen\'s Favorite' },
  '克莱门特·艾德礼': { 'en-US': 'Clement Attlee' },
  '战时内阁': { 'en-US': 'Wartime Cabinet' },
  '艾伦·图灵': { 'en-US': 'Alan Turing' },
  '密码破译': { 'en-US': 'Codebreaking' },
  '安东尼·艾登': { 'en-US': 'Anthony Eden' },
  '盟邦协调': { 'en-US': 'Allied Coordination' },
  '击溃无敌舰队': { 'en-US': 'Rout the Spanish Armada' },
  '对所有敌方生物造成2点伤害。': { 'en-US': 'Deal 2 damage to all enemy minions.' },
  '皇家特许': { 'en-US': 'Royal Charter' },
  '抽一张牌并获得2点护甲。': { 'en-US': 'Draw 1 card and gain 2 armor.' },
  '雷达网络': { 'en-US': 'Radar Network' },
  '抽一张牌，并对一个随机敌方生物造成3点伤害。': {
    'en-US': 'Draw 1 card and deal 3 damage to a random enemy minion.',
  },
  '腓特烈大帝': { 'en-US': 'Frederick the Great' },
  '斜线阵': { 'en-US': 'Oblique Order' },
  '帝王技能：对一个敌方生物造成2点伤害。入场时所有友方生物获得+1攻击。': {
    'en-US': 'Hero Skill: Deal 2 damage to an enemy minion. On play, give all friendly minions +1 Attack.',
  },
  '对一个敌方生物造成2点伤害': { 'en-US': 'Deal 2 damage to an enemy minion' },
  '威廉一世': { 'en-US': 'Wilhelm I' },
  '帝国统一': { 'en-US': 'Imperial Unification' },
  '帝王技能：所有友方生物获得+1生命。入场时获得4点护甲。': {
    'en-US': 'Hero Skill: All friendly minions gain +1 Health. On play, gain 4 Armor.',
  },
  '威廉二世': { 'en-US': 'Wilhelm II' },
  '世界政策': { 'en-US': 'Weltpolitik' },
  '帝王技能：对所有敌方生物造成1点伤害。入场时所有友方生物获得+1攻击。': {
    'en-US': 'Hero Skill: Deal 1 damage to all enemy minions. On play, give all friendly minions +1 Attack.',
  },
  '对所有敌方生物造成1点伤害': { 'en-US': 'Deal 1 damage to all enemy minions' },
  '赫尔穆特·冯·毛奇': { 'en-US': 'Helmuth von Moltke' },
  '嘲讽。技能①总参谋部：抽一张牌。技能②普鲁士军改：所有友方生物获得+1生命。技能③决战规划：对一个敌方生物造成4点伤害。': {
    'en-US': 'Taunt. Skill 1: General Staff — draw 1 card. Skill 2: Prussian Army Reform — all friendly minions gain +1 Health. Skill 3: Battle Planning — deal 4 damage to an enemy minion.',
  },
  '总参谋部': { 'en-US': 'General Staff' },
  '普鲁士军改': { 'en-US': 'Prussian Army Reform' },
  '决战规划': { 'en-US': 'Battle Planning' },
  '阿尔布雷希特·冯·鲁恩': { 'en-US': 'Albrecht von Roon' },
  '冲锋。技能①征兵制：召唤一个3/3掷弹兵。技能②铁血动员：所有友方生物获得+1攻击。技能③炮兵支援：对所有敌方生物造成2点伤害。': {
    'en-US': 'Charge. Skill 1: Conscription — summon a 3/3 Grenadier. Skill 2: Iron Mobilization — give all friendly minions +1 Attack. Skill 3: Artillery Support — deal 2 damage to all enemy minions.',
  },
  '征兵制': { 'en-US': 'Conscription' },
  '铁血动员': { 'en-US': 'Iron Mobilization' },
  '召唤一个3/3掷弹兵': { 'en-US': 'Summon a 3/3 Grenadier' },
  '保罗·冯·兴登堡': { 'en-US': 'Paul von Hindenburg' },
  '嘲讽。技能①东线铁壁：获得3点护甲。技能②鲁登道夫协同：所有友方生物获得+1/+1。技能③总动员：召唤一个3/3装甲师。': {
    'en-US': 'Taunt. Skill 1: Eastern Front Bulwark — gain 3 Armor. Skill 2: Ludendorff Coordination — all friendly minions get +1/+1. Skill 3: Total Mobilization — summon a 3/3 Panzer.',
  },
  '东线铁壁': { 'en-US': 'Eastern Front Bulwark' },
  '鲁登道夫协同': { 'en-US': 'Ludendorff Coordination' },
  '总动员': { 'en-US': 'Total Mobilization' },
  '召唤一个3/3装甲师': { 'en-US': 'Summon a 3/3 Panzer' },
  '阿尔弗雷德·冯·提尔皮茨': { 'en-US': 'Alfred von Tirpitz' },
  '突袭。技能①大舰队法案：抽一张牌。技能②远洋威慑：对一个敌方生物造成5点伤害。技能③海军扩张：所有友方生物获得冲锋（本回合）。': {
    'en-US': 'Rush. Skill 1: Navy Laws — draw 1 card. Skill 2: Blue-Water Deterrence — deal 5 damage to an enemy minion. Skill 3: Naval Expansion — all friendly minions gain Charge this turn.',
  },
  '大舰队法案': { 'en-US': 'Navy Laws' },
  '远洋威慑': { 'en-US': 'Blue-Water Deterrence' },
  '海军扩张': { 'en-US': 'Naval Expansion' },
  '所有友方生物获得冲锋（本回合）': { 'en-US': 'All friendly minions gain Charge this turn' },
  '鲁道夫·冯·德尔布吕克': { 'en-US': 'Rudolf von Delbruck' },
  '联邦财政': { 'en-US': 'Federal Finance' },
  '鲁道夫·冯·贝尼希森': { 'en-US': 'Rudolf von Bennigsen' },
  '邦联协商': { 'en-US': 'Confederation Talks' },
  '莱昂哈德·冯·布卢门撒尔': { 'en-US': 'Leonhard von Blumenthal' },
  '参谋调度': { 'en-US': 'Staff Deployment' },
  '一个友方生物获得+1/+2': { 'en-US': 'Give a friendly minion +1/+2' },
  '伯恩哈德·冯·比洛': { 'en-US': 'Bernhard von Bulow' },
  '海军大臣提尔皮茨': { 'en-US': 'Grand Admiral Tirpitz' },
  '舰队扩军': { 'en-US': 'Fleet Expansion' },
  '对一个敌方生物造成3点伤害': { 'en-US': 'Deal 3 damage to an enemy minion' },
  '特奥巴尔德·冯·贝特曼-霍尔维格': { 'en-US': 'Theobald von Bethmann Hollweg' },
  '帝国财政': { 'en-US': 'Imperial Treasury' },
  '北德意志邦联': { 'en-US': 'North German Confederation' },
  '抽一张牌并获得3点护甲。': { 'en-US': 'Draw 1 card and gain 3 armor.' },
  '普法战争': { 'en-US': 'Franco-Prussian War' },
  '对所有敌方生物造成2点伤害，并获得2点护甲。': {
    'en-US': 'Deal 2 damage to all enemy minions and gain 2 armor.',
  },
  '施里芬计划': { 'en-US': 'Schlieffen Plan' },
  '所有友方生物获得冲锋（本回合）。': { 'en-US': 'All friendly minions gain Charge this turn.' },
  '公海舰队': { 'en-US': 'High Seas Fleet' },
  '对一个随机敌方生物造成4点伤害，并抽一张牌。': {
    'en-US': 'Deal 4 damage to a random enemy minion and draw 1 card.',
  },
  'Benjamin Franklin': { 'zh-CN': '本杰明·富兰克林' },
  'William Sherman': { 'zh-CN': '威廉·谢尔曼' },
  'Alexander Hamilton': { 'zh-CN': '亚历山大·汉密尔顿' },
  'William Pitt': { 'zh-CN': '威廉·皮特' },
  'Francis Drake': { 'zh-CN': '弗朗西斯·德雷克' },
  'Robert Walpole': { 'zh-CN': '罗伯特·沃波尔' },
  'Carl von Clausewitz': { 'zh-CN': '卡尔·冯·克劳塞维茨' },
  'Albrecht von Wallenstein': { 'zh-CN': '阿尔布雷希特·冯·华伦斯坦' },
  'Ludwig Erhard': { 'zh-CN': '路德维希·艾哈德' },
  Diplomacy: { 'zh-CN': '外交斡旋' },
  'National Bank': { 'zh-CN': '国家银行' },
  'Parliament Act': { 'zh-CN': '议会法案' },
  'Privateer Raid': { 'zh-CN': '私掠袭击' },
  'Fiscal Policy': { 'zh-CN': '财政政策' },
  'On War': { 'zh-CN': '战争论' },
  'Mercenary Captain': { 'zh-CN': '佣兵统帅' },
  'Economic Miracle': { 'zh-CN': '经济奇迹' },
  'GI (American Soldier)': { 'zh-CN': '大兵' },
  Marine: { 'zh-CN': '海军陆战队' },
  Ranger: { 'zh-CN': '游骑兵' },
  Medic: { 'zh-CN': '战地医护兵' },
  Airborne: { 'zh-CN': '空降兵' },
  'Sherman Tank': { 'zh-CN': '谢尔曼坦克' },
  'Arsenal of Democracy': { 'zh-CN': '民主兵工厂' },
  'Lend-Lease': { 'zh-CN': '租借法案' },
  'Air Superiority': { 'zh-CN': '制空权' },
  'Marshall Plan': { 'zh-CN': '马歇尔计划' },
  'Manhattan Project': { 'zh-CN': '曼哈顿计划' },
  'Monroe Doctrine': { 'zh-CN': '门罗主义' },
  'Ulysses S. Grant': { 'zh-CN': '尤利西斯·格兰特' },
  'George Patton': { 'zh-CN': '乔治·巴顿' },
  'Total War': { 'zh-CN': '总体战' },
  Siege: { 'zh-CN': '围攻' },
  'March to the Sea': { 'zh-CN': '向海进军' },
  'Blitzkrieg Counter': { 'zh-CN': '闪击反制' },
  'Rally the Troops': { 'zh-CN': '号召部队' },
  'Third Army': { 'zh-CN': '第三集团军' },
  Redcoat: { 'zh-CN': '红衫军' },
  Longbowman: { 'zh-CN': '长弓兵' },
  Knight: { 'zh-CN': '骑士' },
  'Royal Guard': { 'zh-CN': '皇家卫队' },
  Privateer: { 'zh-CN': '私掠船' },
  'Man-of-War': { 'zh-CN': '战列舰' },
  'Rule Britannia': { 'zh-CN': '统治不列颠' },
  'Tea Time': { 'zh-CN': '下午茶时光' },
  'Naval Blockade': { 'zh-CN': '海上封锁' },
  'Colonial Expansion': { 'zh-CN': '殖民扩张' },
  'Great Fire': { 'zh-CN': '伦敦大火' },
  'Enclosure Act': { 'zh-CN': '圈地法案' },
  'Duke of Wellington': { 'zh-CN': '惠灵顿公爵' },
  'Admiral Nelson': { 'zh-CN': '纳尔逊上将' },
  Waterloo: { 'zh-CN': '滑铁卢' },
  'Iron Duke': { 'zh-CN': '铁公爵' },
  'Thin Red Line': { 'zh-CN': '薄红线' },
  Trafalgar: { 'zh-CN': '特拉法加' },
  'England Expects': { 'zh-CN': '英格兰所望' },
  Broadside: { 'zh-CN': '齐射' },
  Landsknecht: { 'zh-CN': '雇佣枪兵' },
  Hussar: { 'zh-CN': '骠骑兵' },
  Grenadier: { 'zh-CN': '掷弹兵' },
  Panzer: { 'zh-CN': '装甲战车' },
  'Teutonic Knight': { 'zh-CN': '条顿骑士' },
  Stormtrooper: { 'zh-CN': '突击队' },
  'Blitzkrieg Doctrine': { 'zh-CN': '闪击战学说' },
  Enigma: { 'zh-CN': '恩尼格玛' },
  'Artillery Barrage': { 'zh-CN': '炮火齐射' },
  Fortification: { 'zh-CN': '筑垒工事' },
  'V-2 Rocket': { 'zh-CN': 'V2火箭' },
  'Scorched Earth': { 'zh-CN': '焦土战术' },
  'Otto von Bismarck': { 'zh-CN': '奥托·冯·俾斯麦' },
  'Erwin Rommel': { 'zh-CN': '埃尔温·隆美尔' },
  'Blood and Iron': { 'zh-CN': '铁血政策' },
  Realpolitik: { 'zh-CN': '现实政治' },
  Unification: { 'zh-CN': '统一帝国' },
  'Desert Fox': { 'zh-CN': '沙漠之狐' },
  Blitzkrieg: { 'zh-CN': '闪击战' },
  'Afrika Korps': { 'zh-CN': '非洲军团' },
  'A standard American soldier.': { 'zh-CN': '标准的美军士兵。' },
  'A basic British infantry soldier.': { 'zh-CN': '基础的不列颠步兵。' },
  'A basic German infantry unit.': { 'zh-CN': '基础的德意志步兵单位。' },
  'Rush.': { 'zh-CN': '突袭。' },
  'Charge.': { 'zh-CN': '冲锋。' },
  'Taunt.': { 'zh-CN': '嘲讽。' },
  'Battlecry: Heal all friendly minions for 1.': { 'zh-CN': '战吼：为所有友方生物恢复1点生命。' },
  'Rush. Battlecry: Deal 2 damage to an enemy minion.': { 'zh-CN': '突袭。战吼：对一个敌方生物造成2点伤害。' },
  'Battlecry: Draw a card.': { 'zh-CN': '战吼：抽一张牌。' },
  'Battlecry: Deal 2 damage to an enemy minion.': { 'zh-CN': '战吼：对一个敌方生物造成2点伤害。' },
  'Draw 1 card': { 'zh-CN': '抽一张牌' },
  'Draw a card': { 'zh-CN': '抽一张牌' },
  'Deal 2 damage to a random enemy minion': { 'zh-CN': '对一个随机敌方生物造成2点伤害' },
  'Gain 1 armor': { 'zh-CN': '获得1点护甲' },
  'Gain 2 armor': { 'zh-CN': '获得2点护甲' },
  'Deal 3 damage to an enemy minion': { 'zh-CN': '对一个敌方生物造成3点伤害' },
  'Deal 4 damage to all minions.': { 'zh-CN': '对所有生物造成4点伤害。' },
  'Opponent discards 1 random card.': { 'zh-CN': '对手随机弃一张牌。' },
  'All friendly minions get +1/+1.': { 'zh-CN': '所有友方生物获得+1/+1。' },
  'All friendly minions gain +1/+1.': { 'zh-CN': '所有友方生物获得+1/+1。' },
  'Draw 2 cards.': { 'zh-CN': '抽两张牌。' },
  'Deal 2 damage to all enemy minions.': { 'zh-CN': '对所有敌方生物造成2点伤害。' },
  'Heal all friendly minions for 3.': { 'zh-CN': '为所有友方生物恢复3点生命。' },
  'Charge. Skill 1: Total War — deal 3 damage to all enemy minions. Skill 2: Siege — deal 5 damage to an enemy minion. Skill 3: March to the Sea — all friendly minions gain Charge this turn.': { 'zh-CN': '冲锋。技能1：总体战，对所有敌方生物造成3点伤害。技能2：围攻，对一个敌方生物造成5点伤害。技能3：向海进军，所有友方生物本回合获得冲锋。' },
  'Deal 3 damage to all enemy minions': { 'zh-CN': '对所有敌方生物造成3点伤害' },
  'Deal 5 damage to an enemy minion': { 'zh-CN': '对一个敌方生物造成5点伤害' },
  'All friendly minions gain Charge this turn': { 'zh-CN': '所有友方生物本回合获得冲锋' },
  'Rush. Skill 1: Blitzkrieg Counter — deal 4 damage to an enemy minion. Skill 2: Rally the Troops — all friendly minions get +2/+1. Skill 3: Third Army — summon a 3/3 GI.': { 'zh-CN': '突袭。技能1：闪击反制，对一个敌方生物造成4点伤害。技能2：号召部队，所有友方生物获得+2/+1。技能3：第三集团军，召唤一个3/3大兵。' },
  'Deal 4 damage to an enemy minion': { 'zh-CN': '对一个敌方生物造成4点伤害' },
  'All friendly minions get +2/+1': { 'zh-CN': '所有友方生物获得+2/+1' },
  'Summon a 3/3 GI': { 'zh-CN': '召唤一个3/3大兵' },
  'Taunt. Skill①Waterloo: Deal 5 damage to an enemy minion. Skill②Iron Duke: Gain +0/+3. Skill③Thin Red Line: All friendly minions gain Taunt this turn.': { 'zh-CN': '嘲讽。技能①滑铁卢：对一个敌方生物造成5点伤害。技能②铁公爵：获得+0/+3。技能③薄红线：所有友方生物本回合获得嘲讽。' },
  'Gain +0/+3': { 'zh-CN': '获得+0/+3' },
  'All friendly minions gain Taunt this turn': { 'zh-CN': '所有友方生物本回合获得嘲讽' },
  'Charge. Skill①Trafalgar: Deal 3 damage to all enemy minions. Skill②England Expects: All friendly minions gain +2 attack. Skill③Broadside: Deal 6 damage to an enemy minion.': { 'zh-CN': '冲锋。技能①特拉法加：对所有敌方生物造成3点伤害。技能②英格兰所望：所有友方生物获得+2攻击力。技能③齐射：对一个敌方生物造成6点伤害。' },
  'All friendly minions gain +2 attack': { 'zh-CN': '所有友方生物获得+2攻击力' },
  'Deal 6 damage to an enemy minion': { 'zh-CN': '对一个敌方生物造成6点伤害' },
  'Summon a 2/2 Redcoat.': { 'zh-CN': '召唤一个2/2红衫军。' },
  'Taunt. Skills: Blood and Iron, Realpolitik, Unification.': { 'zh-CN': '嘲讽。技能：铁血政策、现实政治、统一帝国。' },
  'All friendly minions get +1/+2': { 'zh-CN': '所有友方生物获得+1/+2' },
  'Gain 4 armor': { 'zh-CN': '获得4点护甲' },
  'Rush, Charge. Skills: Desert Fox, Blitzkrieg, Afrika Korps.': { 'zh-CN': '突袭、冲锋。技能：沙漠之狐、闪击战、非洲军团。' },
  'Summon a 3/3 Panzer': { 'zh-CN': '召唤一个3/3装甲战车' },
  'Taunt. Battlecry: Gain 2 armor.': { 'zh-CN': '嘲讽。战吼：获得2点护甲。' },
  'Deal 4 damage to a random enemy minion and 1 damage to all enemy minions.': { 'zh-CN': '对一个随机敌方生物造成4点伤害，并对所有敌方生物造成1点伤害。' },
  'Destroy a random enemy minion and a random friendly minion.': { 'zh-CN': '随机消灭一个敌方生物和一个友方生物。' },
  'All friendly minions get +2 attack.': { 'zh-CN': '所有友方生物获得+2攻击力。' },
  'All friendly minions get +3 health and Taunt this turn.': { 'zh-CN': '所有友方生物获得+3生命值，并在本回合获得嘲讽。' },
  '本多忠胜': { 'en-US': 'Honda Tadakatsu' },
  '兵法三十六计': { 'en-US': 'Thirty-Six Stratagems' },
  '兵糧攻め': { 'en-US': 'Starve the Fortress' },
  '兵马俑': { 'en-US': 'Terracotta Warrior' },
  '不败之将': { 'en-US': 'Undefeated General' },
  '步兵基础兵种。': { 'en-US': 'Basic infantry unit.' },
  '参勤交代': { 'en-US': 'Alternate Attendance' },
  '嘲讽。技能①漠北之战：召唤两个汉朝骑兵。技能②河套筑垒：所有友方生物+3生命。技能③龙城飞将：所有敌方生物-2攻击力。': { 'en-US': 'Taunt. Skill 1: Northern Campaign — summon two Han cavalry. Skill 2: Hetao Fortify — all friendly minions gain +3 Health. Skill 3: Flying General — all enemy minions get -2 Attack.' },
  '嘲讽。技能①七つ道具：获得+2生命值。技能②仁王立ち：所有友方生物获得嘲讽（本回合）。技能③立往生：对所有敌方生物造成3点伤害。': { 'en-US': 'Taunt. Skill 1: Seven Tools — gain +2 Health. Skill 2: Niō Stance — all friendly minions gain Taunt this turn. Skill 3: Standing Death — deal 3 damage to all enemy minions.' },
  '嘲讽。技能①蜻蛉切：对一个敌方生物造成4点伤害。技能②不败之将：获得+1/+2。技能③三河武备：所有友方生物获得+1生命。': { 'en-US': 'Taunt. Skill 1: Dragonfly Cutter — deal 4 damage to an enemy minion. Skill 2: Undefeated General — gain +1/+2. Skill 3: Mikawa Armaments — all friendly minions gain +1 Health.' },
  '嘲讽。技能①征兵令：召唤一个2/2铁炮兵。技能②陆军整训：所有友方生物获得突袭（本回合）。技能③军制改革：获得3点护甲。': { 'en-US': 'Taunt. Skill 1: Conscription Edict — summon a 2/2 Arquebusier. Skill 2: Army Drill — all friendly minions gain Rush this turn. Skill 3: Military Reform — gain 3 Armor.' },
  '嘲讽。寺院的守护者。': { 'en-US': 'Taunt. Guardian of the monastery.' },
  '嘲讽。万里长城永不倒。': { 'en-US': 'Taunt. The Great Wall stands forever.' },
  '持续妙计（2回合）：所有手牌费用-1。': { 'en-US': 'Ongoing stratagem (2 turns): All cards in hand cost 1 less.' },
  '赤备突击': { 'en-US': 'Red Raid' },
  '赤備え': { 'en-US': 'Red Arms' },
  '赤甲军': { 'en-US': 'Red Armor Corps' },
  '冲锋。动员：若你本回合已使用≥3张牌，抽一张牌。': { 'en-US': 'Charge. Mobilize: If you have played 3 or more cards this turn, draw a card.' },
  '冲锋。技能①维新先锋：所有友方生物获得+1/+1。技能②鹿儿岛义军：召唤一个3/3武者。技能③决死突贯：对一个敌方生物造成4点伤害。': { 'en-US': 'Charge. Skill 1: Restoration Vanguard — all friendly minions get +1/+1. Skill 2: Kagoshima Militia — summon a 3/3 Warrior. Skill 3: Do-or-die Charge — deal 4 damage to an enemy minion.' },
  '冲锋。隐秘的刺客。': { 'en-US': 'Charge. Stealthy assassin.' },
  '大唐精锐': { 'en-US': 'Tang Elite' },
  '德川家康': { 'en-US': 'Tokugawa Ieyasu' },
  '德川先锋': { 'en-US': 'Tokugawa Vanguard' },
  '帝王技能：对一个随机敌方生物造成2点伤害。入场时对所有敌方生物造成1点伤害。': { 'en-US': 'Hero Skill: Deal 2 damage to a random enemy minion. On play, deal 1 damage to all enemy minions.' },
  '帝王技能：所有友方生物获得+0/+1。入场时获得4点护甲。': { 'en-US': 'Hero Skill: Give all friendly minions +0/+1. On play, gain 4 Armor.' },
  '帝王技能：所有友方生物获得+1/+1。入场时所有友方生物获得+1攻击力。': { 'en-US': 'Hero Skill: Give all friendly minions +1/+1. On play, all friendly minions gain +1 Attack.' },
  '帝王技能：选择一个友方生物，召唤其1/1复制体。入场时所有友方生物获得驻守2回合。': { 'en-US': 'Hero Skill: Choose a friendly minion and summon a 1/1 copy. On play, all friendly minions gain Garrison for 2 turns.' },
  '帝王技能：召唤一个1/1兵马俑。入场时召唤一个兵马俑。': { 'en-US': 'Hero Skill: Summon a 1/1 Terracotta Warrior. On play, summon a Terracotta Warrior.' },
  '帝王技能：召唤一个1/1足轻。入场时抽一张牌。': { 'en-US': 'Hero Skill: Summon a 1/1 Ashigaru. On play, draw a card.' },
  '动员：若你本回合已使用≥2张牌，获得+1/+1。': { 'en-US': 'Mobilize: If you have played 2 or more cards this turn, gain +1/+1.' },
  '对手随机弃一张牌，并在下回合无法抽牌。': { 'en-US': 'Opponent discards a random card and cannot draw next turn.' },
  '对手随机弃一张牌。你下回合无法抽牌。': { 'en-US': 'Opponent discards a random card. You cannot draw next turn.' },
  '对一个敌方生物造成6点伤害': { 'en-US': 'Deal 6 damage to an enemy minion' },
  '对一个随机敌方生物造成2点伤害': { 'en-US': 'Deal 2 damage to a random enemy minion' },
  '焚书坑儒': { 'en-US': 'Burn the Books, Bury the Scholars' },
  '封狼居胥': { 'en-US': 'Fenglang Sacrifice' },
  '冠军侯': { 'en-US': 'Champion Marquis' },
  '汉朝骑兵': { 'en-US': 'Han Cavalry' },
  '汉武帝': { 'en-US': 'Emperor Wu of Han' },
  '河套筑垒': { 'en-US': 'Hetao Fortify' },
  '获得+1/+2': { 'en-US': 'Gain +1/+2' },
  '获得+2/+2': { 'en-US': 'Gain +2/+2' },
  '获得+2生命值': { 'en-US': 'Gain +2 Health' },
  '获得+3/+3和连击': { 'en-US': 'Gain +3/+3 and Combo Strike' },
  '霍去病': { 'en-US': 'Huo Qubing' },
  '禁军统领': { 'en-US': 'Imperial Guard Captain' },
  '井伊直政': { 'en-US': 'Ii Naomasa' },
  '决死突贯': { 'en-US': 'Do-or-die Charge' },
  '军制改革': { 'en-US': 'Military Reform' },
  '立往生': { 'en-US': 'Standing Death' },
  '六文銭': { 'en-US': 'Six Coins' },
  '龙城飞将': { 'en-US': 'Flying General of Dragon City' },
  '陆军整训': { 'en-US': 'Army Drill' },
  '鹿儿岛义军': { 'en-US': 'Kagoshima Militia' },
  '明修栈道': { 'en-US': 'Repair the Plank Road in the Open' },
  '明治天皇': { 'en-US': 'Emperor Meiji' },
  '明治维新': { 'en-US': 'Meiji Restoration' },
  '漠北之战': { 'en-US': 'Northern Desert Campaign' },
  '幕府稳政': { 'en-US': 'Stable Shogunate' },
  '七つ道具': { 'en-US': 'Seven Tools' },
  '切腹': { 'en-US': 'Seppuku' },
  '秦军步兵': { 'en-US': 'Qin Infantry' },
  '秦军弩手': { 'en-US': 'Qin Crossbowman' },
  '秦始皇': { 'en-US': 'Qin Shi Huang' },
  '蜻蛉切': { 'en-US': 'Dragonfly Cutter' },
  '仁王立ち': { 'en-US': 'Niō Stance' },
  '忍術': { 'en-US': 'Ninjutsu' },
  '忍者': { 'en-US': 'Ninja' },
  '三河武备': { 'en-US': 'Mikawa Armaments' },
  '僧兵': { 'en-US': 'Warrior Monk' },
  '山县有朋': { 'en-US': 'Yamagata Aritomo' },
  '神風': { 'en-US': 'Divine Wind' },
  '十文字槍': { 'en-US': 'Cross Spear' },
  '使一个友方生物获得+3/+3。': { 'en-US': 'Give a friendly minion +3/+3.' },
  '侍': { 'en-US': 'Samurai' },
  '随机消灭一个敌方生物。': { 'en-US': 'Destroy a random enemy minion.' },
  '随机消灭一个敌方生物和一个友方生物。': { 'en-US': 'Destroy a random enemy minion and a random friendly minion.' },
  '所有敌方生物-2攻击力': { 'en-US': 'All enemy minions get -2 Attack' },
  '所有友方生物获得+0/+1': { 'en-US': 'Give all friendly minions +0/+1' },
  '所有友方生物获得+1/+1，并抽一张牌。': { 'en-US': 'Give all friendly minions +1/+1 and draw a card.' },
  '所有友方生物获得+2/+2。': { 'en-US': 'Give all friendly minions +2/+2.' },
  '所有友方生物获得+3生命值': { 'en-US': 'Give all friendly minions +3 Health' },
  '所有友方生物获得+3生命值和嘲讽（本回合）。': { 'en-US': 'Give all friendly minions +3 Health and Taunt this turn.' },
  '所有友方生物获得嘲讽（本回合）': { 'en-US': 'All friendly minions gain Taunt this turn' },
  '锁国令': { 'en-US': 'Sakoku Edict' },
  '唐太宗': { 'en-US': 'Emperor Taizong' },
  '天可汗': { 'en-US': 'Heavenly Khagan' },
  '天威浩荡': { 'en-US': 'Heaven\'s Majesty' },
  '天下布武': { 'en-US': 'Tenka Fubu' },
  '突袭、冲锋。技能①长驱直入：对一个敌方生物造成6点伤害。技能②封狼居胥：+3/+3并获得连击。技能③冠军侯：所有友方生物获得冲锋（本回合）。': { 'en-US': 'Rush, Charge. Skill 1: Drive Deep — deal 6 damage to an enemy minion. Skill 2: Fenglang Sacrifice — gain +3/+3 and Combo Strike. Skill 3: Champion Marquis — all friendly minions gain Charge this turn.' },
  '突袭、冲锋、连击。技能①长驱直入：对一个敌方生物造成6点伤害。技能②封狼居胥：+3/+3并获得连击。技能③冠军侯：所有友方生物获得冲锋（本回合）。': { 'en-US': 'Rush, Charge, Combo Strike. Skill 1: Drive Deep — deal 6 damage to an enemy minion. Skill 2: Fenglang Sacrifice — gain +3/+3 and Combo Strike. Skill 3: Champion Marquis — all friendly minions gain Charge this turn.' },
  '突袭、冲锋。技能①赤备突击：对一个敌方生物造成3点伤害。技能②德川先锋：所有友方生物获得+1攻击。技能③赤甲军：召唤一个1/1足轻。': { 'en-US': 'Rush, Charge. Skill 1: Red Raid — deal 3 damage to an enemy minion. Skill 2: Tokugawa Vanguard — all friendly minions gain +1 Attack. Skill 3: Red Armor Corps — summon a 1/1 Ashigaru.' },
  '突袭、冲锋。技能①十文字槍：对一个敌方生物造成4点伤害。技能②赤備え：获得+2/+2。技能③六文銭：所有友方生物获得突袭（本回合）。': { 'en-US': 'Rush, Charge. Skill 1: Cross Spear — deal 4 damage to an enemy minion. Skill 2: Red Arms — gain +2/+2. Skill 3: Six Coins — all friendly minions gain Rush this turn.' },
  '突袭。火绳枪之力。': { 'en-US': 'Rush. Power of the matchlock.' },
  '亡语：抽一张牌。': { 'en-US': 'Deathrattle: Draw a card.' },
  '维新先锋': { 'en-US': 'Restoration Vanguard' },
  '卫青': { 'en-US': 'Wei Qing' },
  '文明开化': { 'en-US': 'Civilization and Enlightenment' },
  '巫蛊之祸': { 'en-US': 'Witchcraft Purge' },
  '武士道': { 'en-US': 'Bushidō' },
  '武蔵坊弁慶': { 'en-US': 'Musashibō Benkei' },
  '武者': { 'en-US': 'Warrior' },
  '西乡隆盛': { 'en-US': 'Saigō Takamori' },
  '消灭一个友方生物，抽两张牌。': { 'en-US': 'Destroy a friendly minion. Draw two cards.' },
  '选择一个友方生物，召唤其1/1复制体': { 'en-US': 'Choose a friendly minion. Summon a 1/1 copy of it.' },
  '一所懸命': { 'en-US': 'All-out Effort' },
  '战吼：抽一张牌。': { 'en-US': 'Battlecry: Draw a card.' },
  '战吼：所有友方生物获得+1/+1。': { 'en-US': 'Battlecry: Give all friendly minions +1/+1.' },
  '长城守卫': { 'en-US': 'Great Wall Warden' },
  '长驱直入': { 'en-US': 'Drive Deep' },
  '关中戍兵': { 'en-US': 'Guanzhong Garrison Soldier' },
  '召唤兵马俑': { 'en-US': 'Summon Terracotta Warrior' },
  '召唤两个1/1足轻。': { 'en-US': 'Summon two 1/1 Ashigaru.' },
  '召唤两个汉朝骑兵': { 'en-US': 'Summon two Han cavalry' },
  '召唤一个1/1兵马俑': { 'en-US': 'Summon a 1/1 Terracotta Warrior' },
  '召唤一个1/1足轻': { 'en-US': 'Summon a 1/1 Ashigaru' },
  '召唤一个2/2铁炮兵': { 'en-US': 'Summon a 2/2 Arquebusier' },
  '召唤一个3/3武者': { 'en-US': 'Summon a 3/3 Warrior' },
  '列阵齐射的秦军弩手。': { 'en-US': 'A Qin crossbowman trained for disciplined volley fire.' },
  '驻守边关的精锐士卒。': { 'en-US': 'An elite soldier stationed to guard the frontier.' },
  '真田幸村': { 'en-US': 'Sanada Yukimura' },
  '征兵令': { 'en-US': 'Conscription Edict' },
  '織田信長': { 'en-US': 'Oda Nobunaga' },
  '鉄砲隊': { 'en-US': 'Arquebus Corps' },
  '驻守：入场时获得驻守标记，持续2回合。': { 'en-US': 'Garrison: On play, gain a Garrison marker for 2 turns.' },
  '筑城令': { 'en-US': 'Castle-Building Edict' },
  '足軽': { 'en-US': 'Ashigaru' },
  '忍者暗杀者': { 'en-US': 'Ninja Assassin' },
  '忍杀：击杀随从后可额外攻击一次。': { 'en-US': 'Assassin: After killing a minion, may attack once more.' },
  '影の忍': { 'en-US': 'Shadow Shinobi' },
  '忍杀。突袭。': { 'en-US': 'Assassin. Rush.' },
  '剣聖': { 'en-US': 'Kensei' },
  '连斩：击杀后可继续攻击。': { 'en-US': 'Combo Strike: After a kill, may continue attacking.' },
  '浪人剣客': { 'en-US': 'Ronin Blade' },
  '连斩。': { 'en-US': 'Combo Strike.' },
  '神風の魂': { 'en-US': 'Kamikaze Spirit' },
  '亡语：对随机一个敌方随从造成3点伤害。': { 'en-US': 'Deathrattle: Deal 3 damage to a random enemy minion.' },
  'Supply Truck': { 'zh-CN': '补给卡车' },
  'Deathrattle: Draw a card.': { 'zh-CN': '亡语：抽一张牌。' },
  'Royal Martyr': { 'zh-CN': '皇家殉道者' },
  'Deathrattle: Restore 3 health to your hero.': { 'zh-CN': '亡语：为你的英雄恢复3点生命。' },
  Volkssturm: { 'zh-CN': '国民突击队' },
  'Deathrattle: Give all friendly minions +1 attack.': { 'zh-CN': '亡语：所有友方随从获得+1攻击力。' },

  // ─── M1 sample card translations (17 cards across 5 civs) ─────────
  '伊贺刺客': { 'en-US': 'Iga Assassin' },
  '鸩毒武者': { 'en-US': 'Venom Bushi' },
  '雾隐忍者': { 'en-US': 'Mist Ninja' },
  '不死武士': { 'en-US': 'Undying Samurai' },
  '武士道圣骑': { 'en-US': 'Bushido Paladin' },
  '转生僧': { 'en-US': 'Reborn Monk' },
  '双刀武士': { 'en-US': 'Twin Blade Samurai' },
  '宫廷卫兵': { 'en-US': 'Palace Guard' },
  '龙骑兵': { 'en-US': 'Dragoon' },
  '皇家近卫': { 'en-US': 'Imperial Guard' },
  '皇家军医': { 'en-US': 'Royal Medic' },
  '闪电步兵': { 'en-US': 'Blitz Trooper' },
  '双刃骠骑': { 'en-US': 'Twin-Saber Hussar' },
  '装甲恢复车': { 'en-US': 'Recovery Tank' },
  '战地工程师': { 'en-US': 'Field Engineer' },
  '民兵盾兵': { 'en-US': 'Militia Shieldman' },
  '蛊师': { 'en-US': 'Gu Sorcerer' },
  '剧毒。': { 'en-US': 'Poisonous.' },
  '剧毒。突袭。': { 'en-US': 'Poisonous. Rush.' },
  '重生。': { 'en-US': 'Reborn.' },
  '重生。战吼：使你的英雄恢复2点生命。': {
    'en-US': 'Reborn. Battlecry: Restore 2 Health to your hero.',
  },
  '风怒。': { 'en-US': 'Windfury.' },
  '圣盾。': { 'en-US': 'Divine Shield.' },
  '圣盾。嘲讽。': { 'en-US': 'Divine Shield. Taunt.' },
  '吸血。': { 'en-US': 'Lifesteal.' },
  '吸血。嘲讽。': { 'en-US': 'Lifesteal. Taunt.' },
};

function localizeText(text: string, locale: SupportedLocale = DEFAULT_LOCALE): string {
  if (!text) {
    return text;
  }

  return TEXT_RESOURCE_TABLE[text]?.[locale] ?? text;
}

export function getHeroSkillDisplayText(
  skill: HeroSkill | undefined,
  locale: SupportedLocale = DEFAULT_LOCALE,
): HeroSkill | undefined {
  if (!skill) {
    return undefined;
  }

  return {
    ...skill,
    name: localizeText(skill.name, locale),
    description: localizeText(skill.description, locale),
  };
}

export function getGeneralSkillsDisplayText(
  skills: GeneralSkill[] | undefined,
  locale: SupportedLocale = DEFAULT_LOCALE,
): GeneralSkill[] | undefined {
  if (!skills) {
    return undefined;
  }

  return skills.map((skill) => ({
    ...skill,
    name: localizeText(skill.name, locale),
    description: localizeText(skill.description, locale),
  }));
}

export function getMinisterSkillDisplayText(
  skill: MinisterSkill,
  locale: SupportedLocale = DEFAULT_LOCALE,
): MinisterSkill {
  return {
    ...skill,
    name: localizeText(skill.name, locale),
    description: localizeText(skill.description, locale),
  };
}

export function getMinisterDisplayText(
  minister: Minister,
  locale: SupportedLocale = DEFAULT_LOCALE,
): Minister {
  return {
    ...minister,
    name: localizeText(minister.name, locale),
    activeSkill: getMinisterSkillDisplayText(minister.activeSkill, locale),
  };
}

export function getMinistersDisplayText(
  ministers: Minister[],
  locale: SupportedLocale = DEFAULT_LOCALE,
): Minister[] {
  return ministers.map((minister) => getMinisterDisplayText(minister, locale));
}

export function getKeywordText(
  keywords: Keyword[],
  locale: SupportedLocale = DEFAULT_LOCALE,
): string {
  const labels = KEYWORD_LABELS[locale] ?? KEYWORD_LABELS[DEFAULT_LOCALE];
  return keywords.map((keyword) => labels[keyword] ?? keyword).join(' ');
}

export function getCardDisplayText<T extends CardTextCarrier>(
  card: T,
  locale: SupportedLocale = DEFAULT_LOCALE,
): T {
  return {
    ...card,
    name: localizeText(card.name, locale),
    description: localizeText(card.description, locale),
    heroSkill: getHeroSkillDisplayText(card.heroSkill, locale),
    generalSkills: getGeneralSkillsDisplayText(card.generalSkills, locale),
  };
}

export function getCardSearchText(
  card: Card,
  locale: SupportedLocale = DEFAULT_LOCALE,
): string {
  const displayCard = getCardDisplayText(card, locale);

  return [displayCard.name, displayCard.description, getKeywordText(displayCard.keywords, locale)]
    .join(' ')
    .toLowerCase();
}